version: '3.8'

services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment: 
      ACCEPT_EULA: "1"
      SA_PASSWORD: "Password@1"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

  redis:
    image: redis:latest
    container_name: my-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  sql-data:
  redis-data:
