version: '3.8'

services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "1"
      SA_PASSWORD: "Password@1"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

  redis:
    image: redis:latest
    container_name: my-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mssql
      KC_DB_URL: "jdbc:sqlserver://sql:1433;databaseName=CryptoTrackerDB;encrypt=false;trustServerCertificate=true"
      KC_DB_USERNAME: sa
      KC_DB_PASSWORD: "Password@1"
      KC_HTTP_PORT: 8082
    command: ["start-dev", "--http-port=8082", "-Dkeycloak.theme.cacheTemplates=false"]
    depends_on:
      - sql
    ports:
      - "8082:8082"
    volumes:
      - "D:/My Data/Projects/CoinHawk/client/keycloak-theme:/opt/keycloak/themes/keycloak-theme:ro"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5203:5203"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5203
    depends_on:
      - sql
      - redis


volumes:
  sql-data:
  redis-data:
