name: Build and Push Docker Images with Compose

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/anasserekysy/cryptotracker-server:latest

jobs:
  checkout-and-prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

  build-image:
    runs-on: ubuntu-latest
    needs: checkout-and-prepare

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image via Docker Compose
        run: IMAGE_NAME=${IMAGE_NAME} docker compose -f docker-compose.yml build

  push-image:
    runs-on: ubuntu-latest
    needs: build-image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Push Docker image via Docker Compose
        run: IMAGE_NAME=${IMAGE_NAME} docker compose -f docker-compose.yml push
