name: CI/CD - Build, Push & Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/anasserekysy/coinhawk-server:latest

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image via Compose
        run: |
          IMAGE_NAME=${IMAGE_NAME} docker compose -f docker-compose.yml build
          IMAGE_NAME=${IMAGE_NAME} docker compose -f docker-compose.yml push

  deploy-to-ovh:
    name: Deploy to OVH
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to OVH via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.OVH_HOST }}
          username: ${{ secrets.OVH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: IMAGE_NAME
          script: |
            echo "IMAGE_NAME = $IMAGE_NAME"
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCR_TOKEN }}
            docker pull $IMAGE_NAME
            docker stop coinhawk || true
            docker rm coinhawk || true
            docker run -d \
              --name coinhawk \
              -p 5203:5203 \
              --restart unless-stopped \
              $IMAGE_NAME
